import React from "react"
import Layout from "../components/Layout"
import AskPanel from "../components/AskPanel"

export default function AskPage() {
  return (
    <Layout title="Ask MummSTER AI" activePage="ask">
      <p className="sb-ask-intro">
        Ask any question about Philadelphia Mummers String Band history in plain English.
        Powered by MummSTER AI — natural language to SQL, with chart generation and plain-English interpretation.
      </p>
      <div style={{
        background: "#111c2d", border: "1px solid #1f3352",
        borderRadius: "8px", padding: "0.75rem 1.1rem",
        marginBottom: "1.5rem", fontSize: "0.78rem", color: "#6e8faf",
        lineHeight: "1.6", display: "flex", gap: "1rem",
        alignItems: "flex-start", flexWrap: "wrap",
      }}>
        <div style={{ flex: 1, minWidth: "200px" }}>
          <span style={{ color: "#9a7e35", fontWeight: 600 }}>ℹ️ About MummSTER AI — </span>
          Answers are generated by AI from historical competition records and may contain
          errors or omissions. Data coverage varies by era — contemporary results
          (2014–present) are most complete. Always verify important facts against
          official sources.
        </div>
        <div style={{ flexShrink: 0, fontSize: "0.75rem" }}>
          <a
            href="mailto:rci27@hotmail.com?subject=MummSTER AI Feedback"
            style={{ color: "#9a7e35", textDecoration: "none" }}
          >
            Report an issue ↗
          </a>
        </div>
      </div>
      <AskPanel />
      <div className="sb-examples">
        <div className="sb-examples-label">Example questions</div>
        <ul>
          <li>Which band has the longest consecutive top-5 streak?</li>
          <li>Compare Ferko and Aqua on Music Playing scores from 2014 to 2024</li>
          <li>What was the highest total score ever recorded in the contemporary era?</li>
          <li>Which bands have never finished outside the top 5?</li>
          <li>How has Fralinger's placement trended over the last 20 years?</li>
        </ul>
      </div>
    </Layout>
  )
}
